// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type AiProvider struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Model     string    `json:"model"`
	Endpoint  string    `json:"endpoint"`
	CliPath   string    `json:"cli_path"`
	CliArgs   string    `json:"cli_args"`
	IsDefault int64     `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Path         string    `json:"path"`
	LastOpenedAt time.Time `json:"last_opened_at"`
}

type Specflow struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	ProviderID  int64     `json:"provider_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	Status      string    `json:"status"`
	Missed      int64     `json:"missed"`
	CreatedAt   time.Time `json:"created_at"`
}

type SpecflowItem struct {
	ID         int64        `json:"id"`
	FlowID     int64        `json:"flow_id"`
	Position   int64        `json:"position"`
	ChangeName string       `json:"change_name"`
	Status     string       `json:"status"`
	Log        string       `json:"log"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}
