// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const clearDefaultAIProvider = `-- name: ClearDefaultAIProvider :exec
UPDATE ai_providers SET is_default = 0
`

func (q *Queries) ClearDefaultAIProvider(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultAIProvider)
	return err
}

const createAIProvider = `-- name: CreateAIProvider :one
INSERT INTO ai_providers (name, kind, model, endpoint, cli_path, cli_args, is_default, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, kind, model, endpoint, cli_path, cli_args, is_default, created_at
`

type CreateAIProviderParams struct {
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Model     string    `json:"model"`
	Endpoint  string    `json:"endpoint"`
	CliPath   string    `json:"cli_path"`
	CliArgs   string    `json:"cli_args"`
	IsDefault int64     `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (AiProvider, error) {
	row := q.db.QueryRowContext(ctx, createAIProvider,
		arg.Name,
		arg.Kind,
		arg.Model,
		arg.Endpoint,
		arg.CliPath,
		arg.CliArgs,
		arg.IsDefault,
		arg.CreatedAt,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Endpoint,
		&i.CliPath,
		&i.CliArgs,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createSpecflow = `-- name: CreateSpecflow :one
INSERT INTO specflows (project_id, provider_id, scheduled_at, status, missed, created_at)
VALUES (?, ?, ?, 'pending', 0, ?)
RETURNING id, project_id, provider_id, scheduled_at, status, missed, created_at
`

type CreateSpecflowParams struct {
	ProjectID   int64     `json:"project_id"`
	ProviderID  int64     `json:"provider_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateSpecflow(ctx context.Context, arg CreateSpecflowParams) (Specflow, error) {
	row := q.db.QueryRowContext(ctx, createSpecflow,
		arg.ProjectID,
		arg.ProviderID,
		arg.ScheduledAt,
		arg.CreatedAt,
	)
	var i Specflow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderID,
		&i.ScheduledAt,
		&i.Status,
		&i.Missed,
		&i.CreatedAt,
	)
	return i, err
}

const createSpecflowItem = `-- name: CreateSpecflowItem :one
INSERT INTO specflow_items (flow_id, position, change_name, status)
VALUES (?, ?, ?, 'pending')
RETURNING id, flow_id, position, change_name, status, log, started_at, finished_at
`

type CreateSpecflowItemParams struct {
	FlowID     int64  `json:"flow_id"`
	Position   int64  `json:"position"`
	ChangeName string `json:"change_name"`
}

func (q *Queries) CreateSpecflowItem(ctx context.Context, arg CreateSpecflowItemParams) (SpecflowItem, error) {
	row := q.db.QueryRowContext(ctx, createSpecflowItem, arg.FlowID, arg.Position, arg.ChangeName)
	var i SpecflowItem
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Position,
		&i.ChangeName,
		&i.Status,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteAIProvider = `-- name: DeleteAIProvider :exec
DELETE FROM ai_providers WHERE id = ?
`

func (q *Queries) DeleteAIProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAIProvider, id)
	return err
}

const deleteSpecflow = `-- name: DeleteSpecflow :exec
;

DELETE FROM specflows WHERE id = ?
`

func (q *Queries) DeleteSpecflow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpecflow, id)
	return err
}

const deleteSpecflowItems = `-- name: DeleteSpecflowItems :exec
DELETE FROM specflow_items WHERE flow_id = ?
`

func (q *Queries) DeleteSpecflowItems(ctx context.Context, flowID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpecflowItems, flowID)
	return err
}

const getAIProvider = `-- name: GetAIProvider :one
SELECT id, name, kind, model, endpoint, cli_path, cli_args, is_default, created_at FROM ai_providers WHERE id = ?
`

func (q *Queries) GetAIProvider(ctx context.Context, id int64) (AiProvider, error) {
	row := q.db.QueryRowContext(ctx, getAIProvider, id)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Endpoint,
		&i.CliPath,
		&i.CliArgs,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, path, last_opened_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastOpenedAt,
	)
	return i, err
}

const getProjectByPath = `-- name: GetProjectByPath :one
SELECT id, name, path, last_opened_at FROM projects WHERE path = ?
`

func (q *Queries) GetProjectByPath(ctx context.Context, path string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByPath, path)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastOpenedAt,
	)
	return i, err
}

const getSpecflow = `-- name: GetSpecflow :one
SELECT id, project_id, provider_id, scheduled_at, status, missed, created_at FROM specflows WHERE id = ?
`

func (q *Queries) GetSpecflow(ctx context.Context, id int64) (Specflow, error) {
	row := q.db.QueryRowContext(ctx, getSpecflow, id)
	var i Specflow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderID,
		&i.ScheduledAt,
		&i.Status,
		&i.Missed,
		&i.CreatedAt,
	)
	return i, err
}

const listAIProviders = `-- name: ListAIProviders :many
SELECT id, name, kind, model, endpoint, cli_path, cli_args, is_default, created_at FROM ai_providers ORDER BY created_at ASC
`

func (q *Queries) ListAIProviders(ctx context.Context) ([]AiProvider, error) {
	rows, err := q.db.QueryContext(ctx, listAIProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiProvider
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Endpoint,
			&i.CliPath,
			&i.CliArgs,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSpecflows = `-- name: ListDueSpecflows :many
SELECT id, project_id, provider_id, scheduled_at, status, missed, created_at FROM specflows
WHERE status = 'pending' AND missed = 0 AND scheduled_at <= ?
`

func (q *Queries) ListDueSpecflows(ctx context.Context, scheduledAt time.Time) ([]Specflow, error) {
	rows, err := q.db.QueryContext(ctx, listDueSpecflows, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specflow
	for rows.Next() {
		var i Specflow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProviderID,
			&i.ScheduledAt,
			&i.Status,
			&i.Missed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, last_opened_at FROM projects ORDER BY last_opened_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecflowItems = `-- name: ListSpecflowItems :many
SELECT id, flow_id, position, change_name, status, log, started_at, finished_at FROM specflow_items
WHERE flow_id = ? ORDER BY position ASC
`

func (q *Queries) ListSpecflowItems(ctx context.Context, flowID int64) ([]SpecflowItem, error) {
	rows, err := q.db.QueryContext(ctx, listSpecflowItems, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecflowItem
	for rows.Next() {
		var i SpecflowItem
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Position,
			&i.ChangeName,
			&i.Status,
			&i.Log,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecflows = `-- name: ListSpecflows :many
SELECT id, project_id, provider_id, scheduled_at, status, missed, created_at FROM specflows ORDER BY scheduled_at ASC
`

func (q *Queries) ListSpecflows(ctx context.Context) ([]Specflow, error) {
	rows, err := q.db.QueryContext(ctx, listSpecflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specflow
	for rows.Next() {
		var i Specflow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProviderID,
			&i.ScheduledAt,
			&i.Status,
			&i.Missed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSpecflowMissed = `-- name: MarkSpecflowMissed :exec
UPDATE specflows SET missed = 1 WHERE id = ?
`

func (q *Queries) MarkSpecflowMissed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSpecflowMissed, id)
	return err
}

const setDefaultAIProvider = `-- name: SetDefaultAIProvider :exec
UPDATE ai_providers SET is_default = 1 WHERE id = ?
`

func (q *Queries) SetDefaultAIProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultAIProvider, id)
	return err
}

const touchProject = `-- name: TouchProject :exec
UPDATE projects SET last_opened_at = ? WHERE path = ?
`

type TouchProjectParams struct {
	LastOpenedAt time.Time `json:"last_opened_at"`
	Path         string    `json:"path"`
}

func (q *Queries) TouchProject(ctx context.Context, arg TouchProjectParams) error {
	_, err := q.db.ExecContext(ctx, touchProject, arg.LastOpenedAt, arg.Path)
	return err
}

const updateAIProvider = `-- name: UpdateAIProvider :one
UPDATE ai_providers SET name = ?, model = ?, endpoint = ?, cli_path = ?, cli_args = ?
WHERE id = ?
RETURNING id, name, kind, model, endpoint, cli_path, cli_args, is_default, created_at
`

type UpdateAIProviderParams struct {
	Name     string `json:"name"`
	Model    string `json:"model"`
	Endpoint string `json:"endpoint"`
	CliPath  string `json:"cli_path"`
	CliArgs  string `json:"cli_args"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) (AiProvider, error) {
	row := q.db.QueryRowContext(ctx, updateAIProvider,
		arg.Name,
		arg.Model,
		arg.Endpoint,
		arg.CliPath,
		arg.CliArgs,
		arg.ID,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Endpoint,
		&i.CliPath,
		&i.CliArgs,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateSpecflowItemPosition = `-- name: UpdateSpecflowItemPosition :exec
UPDATE specflow_items SET position = ? WHERE id = ? AND flow_id = ?
`

type UpdateSpecflowItemPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
	FlowID   int64 `json:"flow_id"`
}

func (q *Queries) UpdateSpecflowItemPosition(ctx context.Context, arg UpdateSpecflowItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateSpecflowItemPosition, arg.Position, arg.ID, arg.FlowID)
	return err
}

const updateSpecflowItemStatus = `-- name: UpdateSpecflowItemStatus :exec
UPDATE specflow_items SET status = ?, log = ?, started_at = ?, finished_at = ? WHERE id = ?
`

type UpdateSpecflowItemStatusParams struct {
	Status     string       `json:"status"`
	Log        string       `json:"log"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	ID         int64        `json:"id"`
}

func (q *Queries) UpdateSpecflowItemStatus(ctx context.Context, arg UpdateSpecflowItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSpecflowItemStatus,
		arg.Status,
		arg.Log,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const updateSpecflowStatus = `-- name: UpdateSpecflowStatus :exec
UPDATE specflows SET status = ? WHERE id = ?
`

type UpdateSpecflowStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateSpecflowStatus(ctx context.Context, arg UpdateSpecflowStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSpecflowStatus, arg.Status, arg.ID)
	return err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (name, path, last_opened_at)
VALUES (?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    name = excluded.name,
    last_opened_at = excluded.last_opened_at
RETURNING id, name, path, last_opened_at
`

type UpsertProjectParams struct {
	Name         string    `json:"name"`
	Path         string    `json:"path"`
	LastOpenedAt time.Time `json:"last_opened_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject, arg.Name, arg.Path, arg.LastOpenedAt)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastOpenedAt,
	)
	return i, err
}
