// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	ClearDefaultAIProvider(ctx context.Context) error
	CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (AiProvider, error)
	CreateSpecflow(ctx context.Context, arg CreateSpecflowParams) (Specflow, error)
	CreateSpecflowItem(ctx context.Context, arg CreateSpecflowItemParams) (SpecflowItem, error)
	DeleteAIProvider(ctx context.Context, id int64) error
	DeleteSpecflow(ctx context.Context, id int64) error
	DeleteSpecflowItems(ctx context.Context, flowID int64) error
	GetAIProvider(ctx context.Context, id int64) (AiProvider, error)
	GetProjectByID(ctx context.Context, id int64) (Project, error)
	GetProjectByPath(ctx context.Context, path string) (Project, error)
	GetSpecflow(ctx context.Context, id int64) (Specflow, error)
	ListAIProviders(ctx context.Context) ([]AiProvider, error)
	ListDueSpecflows(ctx context.Context, scheduledAt time.Time) ([]Specflow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSpecflowItems(ctx context.Context, flowID int64) ([]SpecflowItem, error)
	ListSpecflows(ctx context.Context) ([]Specflow, error)
	MarkSpecflowMissed(ctx context.Context, id int64) error
	SetDefaultAIProvider(ctx context.Context, id int64) error
	TouchProject(ctx context.Context, arg TouchProjectParams) error
	UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) (AiProvider, error)
	UpdateSpecflowItemPosition(ctx context.Context, arg UpdateSpecflowItemPositionParams) error
	UpdateSpecflowItemStatus(ctx context.Context, arg UpdateSpecflowItemStatusParams) error
	UpdateSpecflowStatus(ctx context.Context, arg UpdateSpecflowStatusParams) error
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
